http:
  listener:
    host: "localhost"
    port: "9081"
    path: "/travelOnTipCall/{serviceType}"
    
db:
  mysql:
    host: "sql12.freesqldatabase.com"
    port: "3306"
    user: "sql12597819"
    password: "9SuHth3LSQ"
    name: "sql12597819"
    